spring:
  config:
    import: nacos:article-service-dev.yml
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin@2026

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ice-article?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:

file:
  storage:
    base-url: http://localhost:8080

minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: admin@2026
  bucket: chat-book-images
  public-url: http://localhost:9000
