socket:
  path: /ws

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: uploads
  publicUrl: http://localhost:9000

